### ISSUE TITLE
Solpsis v4 hyperopt error

### ISSUE THREAD

**Issue by Pascal66** [werkkrew/freqtrade-strategies#6]
Hello !
Little problem 
`KeyError: '3d_low_1h'`

**Comment by werkkrew** [comment]
You appear to be trying to use the v3 hyperopt file with the v4 strategy?  Please read the change log.

**Comment by Pascal66** [comment]
That's what I found. Thank you

**Comment by Pascal66** [comment]
2021-04-19 17:21:25,880 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 12
Unexpected error 'BSV/USDT' calling <bound method Solipsis4.custom_stoploss of <Solipsis_v4.Solipsis4 object at 0x7fe743699be0>>
Traceback (most recent call last):
  File "/home/speedoo/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/speedoo/freqtrade/user_data/strategies/Solipsis_v4.py", line 326, in custom_stoploss
    sroc = self.custom_trade_info[trade.pair]['sroc'].loc[current_time]['sroc']
KeyError: 'BSV/USDT'
