### ISSUE TITLE
Still an error with v4 Any clue ?

### ISSUE THREAD

**Issue by Pascal66** [werkkrew/freqtrade-strategies#7]
2021-04-19 17:21:25,880 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 12
Unexpected error 'BSV/USDT' calling <bound method Solipsis4.custom_stoploss of <Solipsis_v4.Solipsis4 object at 0x7fe743699be0>>
Traceback (most recent call last):
File "/home/speedoo/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
return f(*args, **kwargs)
File "/home/speedoo/freqtrade/user_data/strategies/Solipsis_v4.py", line 326, in custom_stoploss
sroc = self.custom_trade_info[trade.pair]['sroc'].loc[current_time]['sroc']
KeyError: 'BSV/USDT'

**Comment by Pascal66** [comment]
Error Located at https://github.com/werkkrew/freqtrade-strategies/blob/2d18ec05264b6098f60d28c3506d19f646485b2e/strategies/Solipsis_v4.py#L326

**Comment by werkkrew** [comment]
Looks like it wasn't able to load the data/populate the indicators for that pair, BSV/USDT

**Comment by Pascal66** [comment]
Error happen for 4 or 5 pairs in the whitelist.

**Comment by werkkrew** [comment]
If you remove those pairs does it work as expected?

**Comment by Pascal66** [comment]
Ok, I resolved a part of that, I deleted all the cache and redownloaded all 5m 1h, now I've another error for BTC/USDT as it's on the blacklist : 
```
2021-04-20 08:55:47,407 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/USDT", timeframe: 5m. Use `freqtrade download-data` to download the data
2021-04-20 08:55:47,407 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 5m).
2021-04-20 08:55:47,418 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/speedoo/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/speedoo/freqtrade/freqtrade/commands/optimize_commands.py", line 86, in start_hyperopt
    hyperopt.start()
  File "/home/speedoo/freqtrade/freqtrade/optimize/hyperopt.py", line 383, in start
    preprocessed = self.backtesting.strategy.ohlcvdata_to_dataframe(data)
  File "/home/speedoo/freqtrade/freqtrade/strategy/interface.py", line 670, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/speedoo/freqtrade/freqtrade/strategy/interface.py", line 670, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/speedoo/freqtrade/freqtrade/strategy/interface.py", line 687, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/speedoo/freqtrade/user_data/strategies/Solipsis_v4.py", line 230, in populate_indicators
    dataframe['BTC_rmi'] = cta.RMI(btc_stake_tf, length=55, mom=5)
  File "/home/speedoo/freqtrade/user_data/strategies/custom_indicators.py", line 58, in RMI
    df["emaInc"] = ta.EMA(df, price='maxup', timeperiod=length)
  File "talib/_abstract.pxi", line 399, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 441, in talib._ta_lib.Function.__call_function
  File "/home/speedoo/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 2930, in talib._ta_lib.EMA
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
```

**Comment by Pascal66** [comment]
Unfortunatly, downloading manually the pair BTC/USDT doesnt resolve the problem
I'm back to the first error.
If I remove those pairs in error, other pairs appear in error ~)

**Comment by Pascal66** [comment]
Ok, need to set `use_custom_stoploss = False`
This is the part that's not working
